#!/bin/bash

echo -n "Building parser... "
make all
echo "Done"
echo


cd Tests
dos2unix * 2>/dev/null

for f in `ls *.in`; do
	code_file=`sed "s/\.in/.s/g" <<< "$f"`
	out_file=`sed "s/\.in/.out/g" <<< "$f"`	
	res_file=`sed "s/\.in/.result/g" <<< "$f"`
	
	echo -n "Running test $f...   "
	
	../hw5 < $f 2>&1> $code_file	
	
	cd ../spim/
	timeout 10 ./spim -file ../Tests/$code_file > ../Tests/$res_file
	cd ../Tests/
	
	diff $out_file $res_file 1>/dev/null
	
	if [[ $? -eq 0 ]]; then
		echo "Pass"
		rm -f $res_file
		rm -f $code_file
	else
		echo "Fail"
		diff $out_file $res_file
		#break 
	fi
	echo "~~~~~~~~~~~~ "
done
